// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['API_KEY'] ?? "",
    appId: '1:439739731106:web:3c2644295babad472b9bfb',
    messagingSenderId: '439739731106',
    projectId: 'mylibrary-ee2d4',
    authDomain: 'mylibrary-ee2d4.firebaseapp.com',
    storageBucket: 'mylibrary-ee2d4.firebasestorage.app',
    measurementId: 'G-E0V64BQ2SY',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['API_KEY'] ?? "",
    appId: '1:439739731106:android:d207e6d6fd9639ad2b9bfb',
    messagingSenderId: '439739731106',
    projectId: 'mylibrary-ee2d4',
    storageBucket: 'mylibrary-ee2d4.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['API_KEY'] ?? "",
    appId: '1:439739731106:ios:61b3c48c43c93bfa2b9bfb',
    messagingSenderId: '439739731106',
    projectId: 'mylibrary-ee2d4',
    storageBucket: 'mylibrary-ee2d4.firebasestorage.app',
    iosBundleId: 'com.example.mylibrary',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['API_KEY'] ?? "",
    appId: '1:439739731106:ios:61b3c48c43c93bfa2b9bfb',
    messagingSenderId: '439739731106',
    projectId: 'mylibrary-ee2d4',
    storageBucket: 'mylibrary-ee2d4.firebasestorage.app',
    iosBundleId: 'com.example.mylibrary',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['API_KEY'] ?? "",
    appId: '1:439739731106:web:9cd880acda037bb12b9bfb',
    messagingSenderId: '439739731106',
    projectId: 'mylibrary-ee2d4',
    authDomain: 'mylibrary-ee2d4.firebaseapp.com',
    storageBucket: 'mylibrary-ee2d4.firebasestorage.app',
    measurementId: 'G-LN5MJWW6HM',
  );
}
